### ISSUE TITLE
Convert "Ultima 7" to "Ultima VII"

### ISSUE THREAD

**Issue by Thunderforge** [exult/exult-web#1]
Throughout the website, the game is referred to as "Ultima 7". As [Wikipedia shows](https://en.wikipedia.org/wiki/Ultima_VII:_The_Black_Gate), the game is properly called "Ultima VII". I think the website should reflect the correct name of the game.

It should be fairly easy to fix this by just doing a find/replace on all instances of "Ultima 7".

**Comment by DominusExult** [comment]
You are correct and frankly it was an embarrassment :)

And sorry for letting it sit so long, I totally forgot about this issue. I fixed it in 5b486ff
